---
title: "Final"
author: "Esteban Arellano"
date: "11/22/2018"
output: html_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fs)
library(stringr)
library(cdlTools)
library(tigris)
library(rgdal) # Tools to create leaflet sp frame
library(leaflet)

income <- read.csv("https://opportunityinsights.org/wp-content/uploads/2018/10/county_outcomes_simple.csv")

neighborhood <- read.csv("https://opportunityinsights.org/wp-content/uploads/2018/10/cty_covariates.csv")

all <- income %>%
  left_join(neighborhood)

```

```{r}
# Preparation for Income shiny
fips <- as_data_frame(fips_codes)

fips <- fips %>%
  mutate(state_code = as.numeric(state_code)) %>%
  mutate(county_code = as.numeric(county_code)) %>%
  mutate(id = paste(county, state, sep = ", ")) %>%
  select(state_code, county_code, state_name, id)

tidy_income <- income %>%
  gather("metric", "value", kfr_pooled_pooled_p25:hisp_female_count) %>%
  mutate(gender = str_extract(string = metric, pattern = "male|female")) %>%
  mutate(race = str_extract(string = metric, pattern = "black|hisp|white")) %>%
  mutate(metric_type = str_extract(string = metric, pattern = "kfr|jail|count")) %>%
  mutate(metric_type = fct_recode(metric_type, income = "kfr")) %>%
  mutate(se = str_detect(string = metric, pattern = "se")) %>% # Categories standard error income values
  mutate(race = fct_recode(race, hispanic = "hisp")) %>%
  rename(state_code = state, county_code = county) %>%
  filter(se != TRUE, metric_type == "income") %>% # Keeps all income, removes standard errors
  left_join(fips)

neighborhood <- neighborhood %>%
  rename(state_code = state, county_code = county)

tidy_all <- tidy_income %>%
  left_join(neighborhood)

tidy_all <- as_data_frame(tidy_all)

tidy_all <- tidy_all[, c(1, 2, 9, 11, 3:8, 12:43)]
```

```{r}
# Preparation for map
map <- tidy_income %>%
  mutate(state_code = ifelse(nchar(state_code) == 1, paste(0, state_code, sep = ""), state_code)) %>%
  mutate(county_code = ifelse(nchar(county_code) == 1, paste("00", county_code, sep = ""), county_code)) %>%
  mutate(county_code = ifelse(nchar(county_code) == 2, paste(0, county_code, sep = ""), county_code)) %>%
  mutate(GEOID = paste(state_code, county_code, sep = "")) %>%
  mutate(state_code = as.numeric(state_code), county_code = as.numeric(county_code)) %>%
  mutate(category = ifelse(is.na(race) & is.na(gender), "all", ifelse(is.na(race), paste("all", gender, sep = "_"), ifelse(is.na(gender), paste("all", race, sep = "_"), paste(race, gender, sep = "_"))))) %>%
  filter(metric_type == "income") %>%
  mutate(value = value * 100) %>%
  select(GEOID, id, category, value) %>%
  group_by(GEOID) %>%
  spread(category, value) %>%
  mutate(black_white_male = (black_male + white_male) / 2, black_white_female = (black_female + white_female) / 2, all_black_white = (all_black + all_white) / 2) %>%
  mutate(black_hispanic_male = (black_male + hispanic_male) / 2, black_hispanic_female = (black_female + hispanic_female) / 2, all_black_hispanic = (all_black + all_hispanic) / 2) %>%
  mutate(hispanic_white_male = (hispanic_male + white_male) / 2, hispanic_white_female = (hispanic_female + white_female) / 2, all_hispanic_white = (all_hispanic + all_white) / 2)

us.map.county <- readOGR(dsn= './cb_2017_us_county_20m', layer = "cb_2017_us_county_20m", stringsAsFactors = FALSE)

# Remove Alaska(2), Hawaii(15), Puerto Rico (72), Guam (66), Virgin Islands (78), American Samoa (60) Mariana Islands (69), Micronesia (64), Marshall Islands (68), Palau (70), Minor Islands (74)
us.map.county <- us.map.county[!us.map.county$STATEFP %in% c("02", "15", "72", "66", "78", "60", "69","64", "68", "70", "74", "81", "84", "86", "87", "89", "71", "76","95", "79"),]

leafmap <- merge(us.map.county, map, by= 'GEOID', duplicateGeoms = TRUE)

popup_dat <- paste0("<strong>County: </strong>",
                    leafmap$id,
                    "<br><strong>Mean Income Rank for Children Whose Parents Were at 25th Percentile: </strong>",
                    leafmap$all, "%")

pal <- colorNumeric("RdYlGn", NULL)

leaflet(data = leafmap) %>% 
  addTiles() %>%
  addPolygons(fillColor = ~pal(all),
              fillOpacity = 0.8,
              color = "#BDBDC3",
              weight = 1,
              popup = popup_dat) %>%
  addLegend("bottomright", pal = pal, values = ~all,
            title = "Mean Income Rank (%)",
            opacity = 1)
```

```{r}
# Preparation for map with neighborhood characteristics of richest counties
rich_map <- map %>%
  filter(all >= 50) %>%
  select(GEOID, id, all)

us.map.county.rich <- us.map.county[us.map.county$GEOID %in% rich_map$GEOID,]

leafmap_rich <- merge(us.map.county.rich, rich_map, by= 'GEOID', duplicateGeoms = TRUE)

popup_dat <- paste0("<strong>County: </strong>",
                    leafmap$id,
                    "<br><strong>Mean Income Rank for Children Whose Parents Were at 25th Percentile: </strong>",
                    leafmap$all, "%")

pal <- colorNumeric("RdYlGn", NULL)

leaflet(data = leafmap_rich) %>% 
  addTiles() %>%
  addPolygons(fillColor = ~pal(all),
              fillOpacity = 0.8,
              color = "#BDBDC3",
              weight = 1,
              popup = popup_dat) %>%
  addLegend("bottomright", pal = pal, values = ~all,
            title = "Mean Income Rank (%)",
            opacity = 1)
```

